apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-app
  labels:
    app: hotstar-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotstar-app
  template:
    metadata:
      labels:
        app: hotstar-app
    spec:
      containers:
        - name: hotstar-app
          image: abhipsapriyadarshinisahoo/hotstar-devops-project-nodejs
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: hotstar-service
spec:
  type: LoadBalancer
  selector:
    app: hotstar-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
